import './globals.css'
import localFont from '@next/font/local'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const drukWide = localFont({
  src: [
    {
      path: './assets/fonts/Druk-Wide-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-drukWide'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${drukWide.variable}`}>{children}</body>
    </html>
  )
}
